x-logging: &json-logging
  options:
    max-size: "10m"
    max-file: "2"
  driver: "json-file"

x-phpenv_defaults: &phpenv_defaults
  - PHP_XDEBUG=${XDEBUG_ENABLE}

services:
  dnsmasq:
    image: andyshinn/dnsmasq
    ports:
      - "53:53/udp"
    command: --address=/${DEV_DOMAIN}/127.0.0.1 --local=/${DEV_DOMAIN}/
    restart: unless-stopped
    cap_add:
      - NET_ADMIN

  apachedev:
    build: ./docker-library/httpd
    image: phpdevbox/apache:dev
    ports:
      - 80:80
      - 443:443
    depends_on:
      - php${PHP_VERSION}dev
      - dnsmasq
    volumes:
      - datauserdev:/home/devuser:ro
      - ./certificates:/etc/apache2/ssl/:ro
    container_name: apachedev
    hostname: ${USERNAME}-apachedev
    environment:
      - PHP_VERSION=${PHP_VERSION}
      - DEV_DOMAIN=${DEV_DOMAIN}
    logging: *json-logging
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s

  # nginxdev:
  #   build: ./docker-library/nginx
  #   image: local/nginx:dev
  #   container_name: nginx-dev
  #   hostname: ${USERNAME}-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./certificates:/etc/nginx/ssl/:ro
  #     - datauserdev:/home/devuser:ro
  #   environment:
  #     - DEV_DOMAIN=${DEV_DOMAIN}
  #     - PHP_VERSION=${PHP_VERSION}
  #   depends_on:
  #     - php${PHP_VERSION}dev
  #   logging: *json-logging
  #   healthcheck:
  #     test: curl --fail http://localhost || exit 1
  #     interval: 30s
  #     retries: 5
  #     start_period: 10s
  #     timeout: 10s

  php83dev:
    build: ./docker-library/php/8.3
    image: phpdevbox/php:8.3-dev
    volumes:
      - datauserdev:/home/devuser
    container_name: php83dev
    hostname: ${USERNAME}-php83dev
    environment: *phpenv_defaults
    logging: *json-logging
  
  php84dev:
    build: ./docker-library/php/8.4
    image: phpdevbox/php:8.4-dev
    volumes:
      - datauserdev:/home/devuser
    container_name: php84dev
    hostname: ${USERNAME}-php84dev
    environment: *phpenv_defaults
    logging: *json-logging

volumes:
  datauserdev:

networks:
  default:
    name: phpdevbox_default
    ipam:
      config:
        - subnet: 172.20.0.0/24
