services:
  nginxdev:
    volumes:
      - /home/devuser/public_html:/home/devuser/public_html

  php83dev:
    volumes:
      - /home/devuser/public_html:/home/devuser/public_html
  
  php84dev:
    volumes:
      - /home/devuser/public_html:/home/devuser/public_html
