#!/bin/bash -
set -e

PHP_FOLDER=php/$PHP_VERSION
HOMEDIR="/home/devuser"
BASHRC_DEVUSER="/usr/local/devuser/bashrc"

# Bashrc profile 
for f in $HOME/.bashrc; do
  if ! grep -Fxq "### CUSTOM DEVUSER BLOCK ###" "$f"; then
    echo -e '\n### CUSTOM DEVUSER BLOCK ###'                             >> "$f"
    echo 'if [ -f "'$BASHRC_DEVUSER'" ]; then'                           >> "$f"
    echo '  . "'$BASHRC_DEVUSER'"'                                       >> "$f"
    echo 'fi'                                                            >> "$f"
    echo '### END CUSTOM DEVUSER BLOCK ###'                              >> "$f"
  fi
done

if command -v sudo >/dev/null 2>&1; then
  if ! grep -Fxq "### CUSTOM DEVUSER BLOCK ###" /root/.bashrc 2>/dev/null; then
    sudo sh -c "echo -e '\n### CUSTOM DEVUSER BLOCK ###' >> /root/.bashrc"
    sudo sh -c "echo 'if [ -f \"$BASHRC_DEVUSER\" ]; then' >> /root/.bashrc"
    sudo sh -c "echo '  . \"$BASHRC_DEVUSER\"' >> /root/.bashrc"
    sudo sh -c "echo 'fi' >> /root/.bashrc"
    sudo sh -c "echo '### END CUSTOM DEVUSER BLOCK ###' >> /root/.bashrc"
  fi
fi

if [ "$PHP_XDEBUG" == "yes" ] ; then
  /usr/local/bin/xdebug --force-activate
fi

# if [ "$PHP_XDEBUG" == "no" ] ; then
#   /usr/local/bin/xdebug --force-deactivate
# fi

if [ -s $HOMEDIR/script/cron_devuser ]
then
    chown devuser:www-data $HOMEDIR/script/cron_devuser
    crontab -u www-data $HOMEDIR/script/cron_devuser
fi

# create public_html folder if not present
if [ ! -d "$HOMEDIR/public_html" ]; then
  mkdir -p "$HOMEDIR/public_html"
  chown devuser:www-data $HOMEDIR/public_html
fi

sudo rm /run/cron* -f
sudo /usr/sbin/cron

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php-fpm "$@"
fi

# Si no es root, usar sudo
if [ "$(id -u)" -ne 0 ]; then
	exec sudo "$@"
else
	exec "$@"
fi
